/**
 * Concatenate src/modules into public/engine/pnddrr.bundle.js.
 * Source of truth: the files listed below. Edit those, then run this.
 */
import fs from "fs";
import path from "path";

const FILES = [
  "core/header.js",
  "referentials/data.js",
  "core/state.js",
  "auth/auth.js",
  "shell/nav.js",
  "shell/modal.js",
  "dashboard/dashboard.js",
  "combattants/nouveau.js",
  "combattants/registre.js",
  "demo/seed.js",
  "reintegration/jalons.js",
  "combattants/fiche.js",
  "armes/armes.js",
  "admin/recherche.js",
  "admin/comptes.js",
  "admin/referentiels.js",
  "admin/journal.js",
  "admin/parametres.js",
  "admin/sauvegarde.js",
  "documents/docs.js",
  "reintegration/suivi.js",
  "cartographie/carto.js",
  "admin/import.js",
  "stats/stats.js",
];

const root = "src/modules";
const parts = FILES.map((f) => {
  const dest = path.join(root, f);
  if (!fs.existsSync(dest)) throw new Error("Missing module: " + dest);
  return fs.readFileSync(dest, "utf8");
});

const bundle = `/* PNDDRR engine bundle — generated by scripts/build-engine.mjs — DO NOT EDIT */
/* Source of truth: src/modules/ — run: npm run engine:build */
${parts.join("\n")}
window.__PNDDRR_READY = true;
document.dispatchEvent(new Event("pnddrr-ready"));
`;

fs.mkdirSync("public/engine", { recursive: true });
fs.writeFileSync("public/engine/pnddrr.bundle.js", bundle);
console.log("modules", FILES.length);
console.log("bundle bytes", bundle.length);
