/**
 * Split pnddrr-raw.js into modular engine files and build a classic global bundle.
 * Functions must remain on window so inline onclick handlers keep working.
 */
import fs from "fs";
import path from "path";

const raw = fs.readFileSync("scripts/pnddrr-raw.js", "utf8");

const cuts = [
  { marker: null, file: "core/header.js", start: 0 },
  { marker: "/* ---------- Référentiels ---------- */", file: "referentials/data.js" },
  { marker: "/* ---------- État ---------- */", file: "core/state.js" },
  { marker: "/* ---------- Authentification ---------- */", file: "auth/auth.js" },
  { marker: "/* ---------- Navigation ---------- */", file: "shell/nav.js" },
  { marker: "/* ---------- Modale ---------- */", file: "shell/modal.js" },
  { marker: "/* ================= TABLEAU DE BORD ================= */", file: "dashboard/dashboard.js" },
  { marker: "/* ================= NOUVEL ENREGISTREMENT ================= */", file: "combattants/nouveau.js" },
  { marker: "/* ================= REGISTRE ================= */", file: "combattants/registre.js" },
  { marker: "/* ================= DONNÉES DE DÉMONSTRATION (SIMULATION) ================= */", file: "demo/seed.js" },
  { marker: "/* ================= FORMATION & INTÉGRATION (JALONS) ================= */", file: "reintegration/jalons.js" },
  { marker: "/* ================= FICHE INDIVIDUELLE ================= */", file: "combattants/fiche.js" },
  { marker: "/* ================= REGISTRE DES ARMES ================= */", file: "armes/armes.js" },
  { marker: "/* ================= RECHERCHE MULTICRITÈRE ================= */", file: "admin/recherche.js" },
  { marker: "/* ================= COMPTES ================= */", file: "admin/comptes.js" },
  { marker: "/* ================= RÉFÉRENTIELS — GROUPES ARMÉS ================= */", file: "admin/referentiels.js" },
  { marker: "/* ================= JOURNAL ================= */", file: "admin/journal.js" },
  { marker: "/* ================= SAUVEGARDE & EXPORTS ================= */", file: "admin/sauvegarde.js" },
  { marker: "/* ================= DOCUMENTS IMPRIMABLES ================= */", file: "documents/docs.js" },
  { marker: "/* ================= PARTIE 2 — SUIVI DES RÉINTÉGRATIONS ================= */", file: "reintegration/suivi.js" },
  { marker: "/* ================= PARTIE 3 — CARTOGRAPHIE DES ZONES DE DÉSARMEMENT ================= */", file: "cartographie/carto.js" },
  { marker: "/* ================= STATISTIQUES DU PROGRAMME ================= */", file: "stats/stats.js" },
];

const positions = cuts.map((c) => {
  if (c.start === 0) return { ...c, index: 0 };
  const index = raw.indexOf(c.marker);
  if (index < 0) throw new Error("Marker not found: " + c.marker);
  return { ...c, index };
});

positions.sort((a, b) => a.index - b.index);

const outRoot = "src/modules";
const files = [];

for (let i = 0; i < positions.length; i++) {
  const cur = positions[i];
  const end = i + 1 < positions.length ? positions[i + 1].index : raw.length;
  const chunk = raw.slice(cur.index, end);
  const dest = path.join(outRoot, cur.file);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const banner = `/* module: ${cur.file} — PNDDRR engine (classic globals) */\n`;
  fs.writeFileSync(dest, banner + chunk);
  files.push(cur.file);
  console.log("wrote", dest, chunk.length);
}

const parts = files.map((f) => fs.readFileSync(path.join(outRoot, f), "utf8"));
const bundle = `/* PNDDRR engine bundle — generated by scripts/split-engine.mjs — DO NOT EDIT */
/* Source modules live under src/modules/ — run: npm run engine:build */
${parts.join("\n")}
window.__PNDDRR_READY = true;
document.dispatchEvent(new Event("pnddrr-ready"));
`;

fs.mkdirSync("public/engine", { recursive: true });
fs.writeFileSync("public/engine/pnddrr.bundle.js", bundle);
fs.writeFileSync(
  "scripts/engine-manifest.json",
  JSON.stringify({ files, generatedAt: new Date().toISOString() }, null, 2)
);
console.log("bundle bytes", bundle.length);
